# Generated by Django 3.0.10 on 2021-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prtx_faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
