# Generated by Django 3.0.10 on 2021-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prtx_faq", "0002_faq_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqcategory",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
